version: '1'

services:

  redis:
    image: redis:4.0.11

  g_cabs_combiner:
    build: .
    image: transpred
    container_name: g_cabs_combiner
    command: ./combiner_gcabs.sh 2016 2017
    volumes:
      - transpred-vol:/app
    depends_on:
      - redis

  g_cabs_fetcher:
    build: .
    image: transpred
    container_name: g_cabs_fetcher
    command: ./fetcher_gcabs.sh
    volumes:
      - transpred-vol:/app
    depends_on:
      - redis
      - g_cabs_combiner
    deploy:
      mode: replicated
      replicas: 8

  y_cabs_combiner:
    build: .
    image: transpred
    container_name: y_cabs_combiner
    command: ./combiner_ycabs.sh 2016 2017
    volumes:
      - transpred-vol:/app
    depends_on:
      - redis

  y_cabs_fetcher:
    build: .
    image: transpred
    container_name: y_cabs_fetcher
    command: ./fetcher_ycabs.sh
    volumes:
      - transpred-vol:/app
    depends_on:
      - redis
      - y_cabs_combiner
    deploy:
      mode: replicated
      replicas: 8

  turnstile_combiner:
    build: .
    image: transpred
    container_name: turnstile_combiner
    command: ./combiner_turnstile.sh 2016 2017
    volumes:
      - transpred-vol:/app
    depends_on:
      - redis

  turnstile_fetcher:
      build: .
      image: transpred
      container_name: turnstile_fetcher
      command: ./fetcher_turnstile.sh
      volumes:
        - transpred-vol:/app
      depends_on:
        - redis
        - turnstile_combiner
      deploy:
        mode: replicated
        replicas: 24

  stations_fetcher:
      build: .
      image: transpred
      container_name: stations_fetcher
      command: ./stations.sh
      volumes:
        - transpred-vol:/app

  traffic_combiner:
    build: .
    image: transpred
    container_name: traffic_combiner
    command: ./combiner_traffic.sh 2016 2017
    volumes:
      - transpred-vol:/app
    depends_on:
      - redis

  traffic_fetcher:
      build: .
      image: transpred
      container_name: traffic_fetcher
      command: ./fetcher_traffic.sh
      volumes:
        - transpred-vol:/app
      depends_on:
        - redis
        - traffic_combiner
      deploy:
        mode: replicated
        replicas: 20