version: '3.6'

services:

  #redis:
    #image: redis:4.0.11

  docker:
    image: docker:latest

  g_cabs_combiner:
    build: .
    image: sirisurab/transpred:latest
    container_name: g_cabs_combiner
    links:
      - docker
    command: ./bin/combiner_gcabs.sh 2016 2017
    volumes:
      - transpred-vol:/app
    #depends_on:
      #- redis

  g_cabs_fetcher:
    build: .
    image: sirisurab/transpred:latest
    container_name: g_cabs_fetcher
    links:
      - docker
    command: ./bin/fetcher_gcabs.sh
    volumes:
      - transpred-vol:/app
    depends_on:
      - g_cabs_combiner
    deploy:
      mode: replicated
      replicas: 8

  y_cabs_combiner:
    build: .
    image: sirisurab/transpred:latest
    container_name: y_cabs_combiner
    links:
      - docker
    command: ./bin/combiner_ycabs.sh 2016 2017
    volumes:
      - transpred-vol:/app
    #depends_on:
      #- redis

  y_cabs_fetcher:
    build: .
    image: sirisurab/transpred:latest
    container_name: y_cabs_fetcher
    links:
      - docker
    command: ./bin/fetcher_ycabs.sh
    volumes:
      - transpred-vol:/app
    depends_on:
      - y_cabs_combiner
    deploy:
      mode: replicated
      replicas: 8

  turnstile_combiner:
    build: .
    image: sirisurab/transpred:latest
    container_name: turnstile_combiner
    links:
      - docker
    command: ./bin/combiner_turnstile.sh 2016 2017
    volumes:
      - transpred-vol:/app
    #depends_on:
      #- redis

  turnstile_fetcher:
    build: .
    image: sirisurab/transpred:latest
    container_name: turnstile_fetcher
    links:
      - docker
    command: ./bin/fetcher_turnstile.sh
    volumes:
      - transpred-vol:/app
    depends_on:
      - turnstile_combiner
    deploy:
      mode: replicated
      replicas: 24

  stations_fetcher:
    build: .
    image: sirisurab/transpred:latest
    container_name: stations_fetcher
    command: ./bin/stations.sh
    volumes:
      - transpred-vol:/app

  traffic_combiner:
    build: .
    image: sirisurab/transpred:latest
    container_name: traffic_combiner
    links:
      - docker
    command: ./bin/combiner_traffic.sh 2016 2017
    volumes:
      - transpred-vol:/app
    #depends_on:
      #- redis

  traffic_fetcher:
    build: .
    image: sirisurab/transpred:latest
    container_name: traffic_fetcher
    links:
      - docker
    command: ./bin/fetcher_traffic.sh
    volumes:
      - transpred-vol:/app
    depends_on:
      - traffic_combiner
    deploy:
      mode: replicated
      replicas: 20

volumes:
  transpred-vol: