name: transpred

dependencies:
  - pandas=0.23.0
#  - dask=0.19.2
#  - s3fs
  - pip:
    - fuzzywuzzy
    - python-Levenshtein
    - minio
    - redis
    - s3fs
    - dask[complete]
#    - dask[dataframe]
    - distributed
    - fastparquet
    - geopandas
    - Rtree
    - descartes
    - bokeh
    - wget
    - chardet