name: transpred

dependencies:
  - pip:
    - pandas
    - fuzzywuzzy
    - python-Levenshtein
    - dask[dataframe]
    - fastparquet
    - redis
    - geopandas
    - Rtree
    - descartes
    - bokeh
    - wget
    - minio
