name: transpred

dependencies:
  - pandas=0.23.0
  - pip:
    - fuzzywuzzy
    - python-Levenshtein
    - minio
    - redis
    - s3fs
    - dask[complete]
    - distributed
    - fastparquet
    - lz4
    - geopandas
    - Rtree
    - descartes
    - bokeh
    - wget
    - chardet
    - requests
    - matplotlib
    - seaborn
    - geog
