name: transpred

dependencies:
  - pandas=0.23.0
  - pip:
    - fuzzywuzzy
    - python-Levenshtein
    - minio
    - redis
    - s3fs
    - dask[dataframe]
    - dask[distributed]
    - fastparquet
    - geopandas
    - Rtree
    - descartes
    - bokeh
    - wget